# Generated by Django 4.0.5 on 2022-07-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_product_tag_product_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
